# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ]
